name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  server_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            eeg1412/wikimoe-blog-nuxt-server
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }},eeg1412/wikimoe-blog-nuxt-server:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }},eeg1412/wikimoe-blog-nuxt-server:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64

  blog_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta for blog
        id: meta_blog
        uses: docker/metadata-action@v4
        with:
          images: |
            eeg1412/wikimoe-blog-nuxt
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU for blog
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx for blog
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub for blog
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker for blog
        uses: docker/build-push-action@v3
        with:
          context: ./blog
          platforms: linux/amd64
          tags: ${{ steps.meta_blog.outputs.tags }},eeg1412/wikimoe-blog-nuxt:latest
          labels: ${{ steps.meta_blog.outputs.labels }}
      - name: Build and push for blog
        id: docker_build_blog
        uses: docker/build-push-action@v3
        with:
          context: ./blog
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta_blog.outputs.tags }},eeg1412/wikimoe-blog-nuxt:latest
          labels: ${{ steps.meta_blog.outputs.labels }}
          platforms: linux/amd64
